//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.RemoteSupport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.RemoteSupport.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddButtonText {
            get {
                return ResourceManager.GetString("AddButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned.
        /// </summary>
        public static string AssignedText {
            get {
                return ResourceManager.GetString("AssignedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The support team picked up your request #{0}. A specialist will contact you soon..
        /// </summary>
        public static string AssignedTicketUserNotification {
            get {
                return ResourceManager.GetString("AssignedTicketUserNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign to me.
        /// </summary>
        public static string AssignToMeActionChoiceTitle {
            get {
                return ResourceManager.GetString("AssignToMeActionChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while saving your request. Please try again in few minutes..
        /// </summary>
        public static string AzureStorageErrorText {
            get {
                return ResourceManager.GetString("AzureStorageErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert list.
        /// </summary>
        public static string BotCommandExpertList {
            get {
                return ResourceManager.GetString("BotCommandExpertList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New request.
        /// </summary>
        public static string BotCommandNewRequest {
            get {
                return ResourceManager.GetString("BotCommandNewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change status.
        /// </summary>
        public static string ChangeStatusButtonText {
            get {
                return ResourceManager.GetString("ChangeStatusButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string ChatTextButton {
            get {
                return ResourceManager.GetString("ChatTextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseActionChoiceTitle {
            get {
                return ResourceManager.GetString("CloseActionChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This request is closed and cannot be edited.
        /// </summary>
        public static string ClosedErrorMessage {
            get {
                return ResourceManager.GetString("ClosedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string ClosedText {
            get {
                return ResourceManager.GetString("ClosedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This request with ticket number #{0} is resolved. Make a new request if you still need help..
        /// </summary>
        public static string ClosedTicketUserNotification {
            get {
                return ResourceManager.GetString("ClosedTicketUserNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started now....
        /// </summary>
        public static string ContentText {
            get {
                return ResourceManager.GetString("ContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on .
        /// </summary>
        public static string CreatedOnText {
            get {
                return ResourceManager.GetString("CreatedOnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated on.
        /// </summary>
        public static string DatetimeTitleText {
            get {
                return ResourceManager.GetString("DatetimeTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date selected must be in the past.
        /// </summary>
        public static string DateValidationText {
            get {
                return ResourceManager.GetString("DateValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe the problem.
        /// </summary>
        public static string DesciptionPlaceHolderText {
            get {
                return ResourceManager.GetString("DesciptionPlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required.
        /// </summary>
        public static string DescriptionValidationText {
            get {
                return ResourceManager.GetString("DescriptionValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit request.
        /// </summary>
        public static string EditRequestTitle {
            get {
                return ResourceManager.GetString("EditRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditTicketActionText {
            get {
                return ResourceManager.GetString("EditTicketActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The support team has received your request #{0}..
        /// </summary>
        public static string EndUserNotificationText {
            get {
                return ResourceManager.GetString("EndUserNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Try again in a few minutes..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escalate.
        /// </summary>
        public static string EscalateButtonText {
            get {
                return ResourceManager.GetString("EscalateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Hit **Current on-call team** button to set up on call experts from this team..
        /// </summary>
        public static string ExperListBulletPoint {
            get {
                return ResourceManager.GetString("ExperListBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert List.
        /// </summary>
        public static string ExpertList {
            get {
                return ResourceManager.GetString("ExpertList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter one or more names or emails.
        /// </summary>
        public static string ExpertListPlaceHolderText {
            get {
                return ResourceManager.GetString("ExpertListPlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current on-call team.
        /// </summary>
        public static string ExpertListTitle {
            get {
                return ResourceManager.GetString("ExpertListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a specialist.
        /// </summary>
        public static string ExpertNameTitle {
            get {
                return ResourceManager.GetString("ExpertNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First observed on.
        /// </summary>
        public static string FirstObservedText {
            get {
                return ResourceManager.GetString("FirstObservedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View details.
        /// </summary>
        public static string GoToOriginalThreadButtonText {
            get {
                return ResourceManager.GetString("GoToOriginalThreadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request no {0}- attention required.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This bot has not been added for this team.
        /// </summary>
        public static string InvalidTeamText {
            get {
                return ResourceManager.GetString("InvalidTeamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid tenant detected.
        /// </summary>
        public static string InvalidTenantText {
            get {
                return ResourceManager.GetString("InvalidTenantText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string ManageExpertsActionText {
            get {
                return ResourceManager.GetString("ManageExpertsActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage list of on-call experts here.
        /// </summary>
        public static string ManageExpertsTitle {
            get {
                return ResourceManager.GetString("ManageExpertsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A maximum of 15 people can be added to the list with a min of 0.
        /// </summary>
        public static string MaxOnCallExpertsAllowedText {
            get {
                return ResourceManager.GetString("MaxOnCallExpertsAllowedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi Team, I need immediate support for request created by {0}. Can you help?.
        /// </summary>
        public static string MessageContent {
            get {
                return ResourceManager.GetString("MessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameTitleText {
            get {
                return ResourceManager.GetString("NameTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Hit the  **New request** button or type **New request** in this chat..
        /// </summary>
        public static string NewRequestBulletPoint {
            get {
                return ResourceManager.GetString("NewRequestBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New request.
        /// </summary>
        public static string NewRequestButtonText {
            get {
                return ResourceManager.GetString("NewRequestButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New request.
        /// </summary>
        public static string NewRequestTitle {
            get {
                return ResourceManager.GetString("NewRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find any matches..
        /// </summary>
        public static string NoMatchesFoundText {
            get {
                return ResourceManager.GetString("NoMatchesFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No one is on call right now. Select **Manage** to add specialists to the on-call team..
        /// </summary>
        public static string NoOnCallExpertsConfiguredText {
            get {
                return ResourceManager.GetString("NoOnCallExpertsConfiguredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string NormalText {
            get {
                return ResourceManager.GetString("NormalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no on-call history available..
        /// </summary>
        public static string NoUpdateHistoryText {
            get {
                return ResourceManager.GetString("NoUpdateHistoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The on-call experts list has been modified. {0} have been added..
        /// </summary>
        public static string OnCallExpertMentionText {
            get {
                return ResourceManager.GetString("OnCallExpertMentionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The on-call experts list is modified..
        /// </summary>
        public static string OnCallListUpdateMessage {
            get {
                return ResourceManager.GetString("OnCallListUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here&apos;s the current on-call team. Click **Manage** to change which specialists are on the team..
        /// </summary>
        public static string OnCallSMEDetailCardText {
            get {
                return ResourceManager.GetString("OnCallSMEDetailCardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopen.
        /// </summary>
        public static string ReopenActionChoiceTitle {
            get {
                return ResourceManager.GetString("ReopenActionChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopen and assign to me..
        /// </summary>
        public static string ReopenAssignToMeActionChoiceTitle {
            get {
                return ResourceManager.GetString("ReopenAssignToMeActionChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re changing who works on your request. We&apos;ll update you soon..
        /// </summary>
        public static string ReopenedTicketUserNotification {
            get {
                return ResourceManager.GetString("ReopenedTicketUserNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The support team changed the severity level on your request #{0}..
        /// </summary>
        public static string RequestActionTicketUserNotification {
            get {
                return ResourceManager.GetString("RequestActionTicketUserNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request details.
        /// </summary>
        public static string RequestDetailsText {
            get {
                return ResourceManager.GetString("RequestDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request number.
        /// </summary>
        public static string RequestNumberText {
            get {
                return ResourceManager.GetString("RequestNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string RequestStatusText {
            get {
                return ResourceManager.GetString("RequestStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For reference, here&apos;s what I shared with the on-call team..
        /// </summary>
        public static string RequestSubmittedContent {
            get {
                return ResourceManager.GetString("RequestSubmittedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request sent.
        /// </summary>
        public static string RequestSubmittedText {
            get {
                return ResourceManager.GetString("RequestSubmittedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request type.
        /// </summary>
        public static string RequestTypeText {
            get {
                return ResourceManager.GetString("RequestTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request updated.
        /// </summary>
        public static string RequestUpdatedText {
            get {
                return ResourceManager.GetString("RequestUpdatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send request.
        /// </summary>
        public static string SendRequestButtonText {
            get {
                return ResourceManager.GetString("SendRequestButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired. Please sign in again to proceed..
        /// </summary>
        public static string SessionExpired {
            get {
                return ResourceManager.GetString("SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change severity.
        /// </summary>
        public static string SeverityButtonText {
            get {
                return ResourceManager.GetString("SeverityButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This request is now assigned to {0}..
        /// </summary>
        public static string SmeAssignedStatus {
            get {
                return ResourceManager.GetString("SmeAssignedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status changed to resolved by {0}..
        /// </summary>
        public static string SmeClosedStatus {
            get {
                return ResourceManager.GetString("SmeClosedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This request is modified by {0}..
        /// </summary>
        public static string SmeEditNotificationText {
            get {
                return ResourceManager.GetString("SmeEditNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is requesting support..
        /// </summary>
        public static string SmeRequestDetailText {
            get {
                return ResourceManager.GetString("SmeRequestDetailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity changed to {0} by {1}..
        /// </summary>
        public static string SmeSeverityStatus {
            get {
                return ResourceManager.GetString("SmeSeverityStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status changed to unassigned by {0}..
        /// </summary>
        public static string SmeUnassignedStatus {
            get {
                return ResourceManager.GetString("SmeUnassignedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RE : Support request {0}..
        /// </summary>
        public static string SmeUserChatMessage {
            get {
                return ResourceManager.GetString("SmeUserChatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This request is withdrawn by {0}..
        /// </summary>
        public static string SmeWithdrawNotificationText {
            get {
                return ResourceManager.GetString("SmeWithdrawNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * To check status, click the small version of my icon near your message formatting options..
        /// </summary>
        public static string StatusCheckBulletPoint {
            get {
                return ResourceManager.GetString("StatusCheckBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * To check requests assignements, click the small version of my icon near your message formatting options..
        /// </summary>
        public static string TeamRequestBulletPoint {
            get {
                return ResourceManager.GetString("TeamRequestBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us about the problem.
        /// </summary>
        public static string TellUsAboutProblemText {
            get {
                return ResourceManager.GetString("TellUsAboutProblemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is it about?.
        /// </summary>
        public static string TitleDisplayText {
            get {
                return ResourceManager.GetString("TitleDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type here....
        /// </summary>
        public static string TitlePlaceHolderText {
            get {
                return ResourceManager.GetString("TitlePlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is required.
        /// </summary>
        public static string TitleValidationText {
            get {
                return ResourceManager.GetString("TitleValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassign.
        /// </summary>
        public static string UnassignActionChoiceTitle {
            get {
                return ResourceManager.GetString("UnassignActionChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned.
        /// </summary>
        public static string UnassignedText {
            get {
                return ResourceManager.GetString("UnassignedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access.
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateActionText {
            get {
                return ResourceManager.GetString("UpdateActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View history.
        /// </summary>
        public static string UpdateHistoryActionText {
            get {
                return ResourceManager.GetString("UpdateHistoryActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent.
        /// </summary>
        public static string UrgentText {
            get {
                return ResourceManager.GetString("UrgentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facing a problem? I can ask the on-call team to look into it..
        /// </summary>
        public static string WelcomeCardContent {
            get {
                return ResourceManager.GetString("WelcomeCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string WelcomeCardTitle {
            get {
                return ResourceManager.GetString("WelcomeCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here&apos;s how it works:.
        /// </summary>
        public static string WelcomeSubHeaderText {
            get {
                return ResourceManager.GetString("WelcomeSubHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, I can help you provide support to people who interact with me and need more assistance..
        /// </summary>
        public static string WelcomeTeamCardContent {
            get {
                return ResourceManager.GetString("WelcomeTeamCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to withdraw the request?.
        /// </summary>
        public static string WithdrawConfirmation {
            get {
                return ResourceManager.GetString("WithdrawConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only active requests can be withdrawn..
        /// </summary>
        public static string WithdrawErrorMessage {
            get {
                return ResourceManager.GetString("WithdrawErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawn.
        /// </summary>
        public static string WithdrawnText {
            get {
                return ResourceManager.GetString("WithdrawnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw.
        /// </summary>
        public static string WithdrawRequestActionText {
            get {
                return ResourceManager.GetString("WithdrawRequestActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request #{0} has been withdrawn. If other problem comes up, make a new request. .
        /// </summary>
        public static string WithdrawText {
            get {
                return ResourceManager.GetString("WithdrawText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
