//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.RemoteSupport.Configuration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.RemoteSupport.Configuration.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert list.
        /// </summary>
        public static string BotCommandExpertList {
            get {
                return ResourceManager.GetString("BotCommandExpertList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of on call experts.
        /// </summary>
        public static string BotCommandExpertListDescription {
            get {
                return ResourceManager.GetString("BotCommandExpertListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New request.
        /// </summary>
        public static string BotCommandNewRequest {
            get {
                return ResourceManager.GetString("BotCommandNewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a request to the on-call team.
        /// </summary>
        public static string BotCommandNewRequestDescription {
            get {
                return ResourceManager.GetString("BotCommandNewRequestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add component.
        /// </summary>
        public static string btnAddComponent {
            get {
                return ResourceManager.GetString("btnAddComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build your form.
        /// </summary>
        public static string btnBuildForm {
            get {
                return ResourceManager.GetString("btnBuildForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string btnLogout {
            get {
                return ResourceManager.GetString("btnLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Box.
        /// </summary>
        public static string checkBox {
            get {
                return ResourceManager.GetString("checkBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check box choice options.
        /// </summary>
        public static string checkBoxOptions {
            get {
                return ResourceManager.GetString("checkBoxOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your component.
        /// </summary>
        public static string componentDropdown {
            get {
                return ResourceManager.GetString("componentDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned.
        /// </summary>
        public static string ComposeExtensionCommandAssigned {
            get {
                return ResourceManager.GetString("ComposeExtensionCommandAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search requests assigned to an expert.
        /// </summary>
        public static string ComposeExtensionCommandAssignedDescription {
            get {
                return ResourceManager.GetString("ComposeExtensionCommandAssignedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned.
        /// </summary>
        public static string ComposeExtensionCommandUnassigned {
            get {
                return ResourceManager.GetString("ComposeExtensionCommandUnassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search unassigned requests not yet assigned to an expert.
        /// </summary>
        public static string ComposeExtensionCommandUnassignedDescription {
            get {
                return ResourceManager.GetString("ComposeExtensionCommandUnassignedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string ComposeExtensionsCommandActive {
            get {
                return ResourceManager.GetString("ComposeExtensionsCommandActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search active requests.
        /// </summary>
        public static string ComposeExtensionsCommandActiveDescription {
            get {
                return ResourceManager.GetString("ComposeExtensionsCommandActiveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string ComposeExtensionsCommandClosed {
            get {
                return ResourceManager.GetString("ComposeExtensionsCommandClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search closed requests.
        /// </summary>
        public static string ComposeExtensionsCommandClosedDescription {
            get {
                return ResourceManager.GetString("ComposeExtensionsCommandClosedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search requests.
        /// </summary>
        public static string ComposeExtensionsCommandParameterDescription {
            get {
                return ResourceManager.GetString("ComposeExtensionsCommandParameterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string ComposeExtensionsCommandParameterSearch {
            get {
                return ResourceManager.GetString("ComposeExtensionsCommandParameterSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent.
        /// </summary>
        public static string ComposeExtensionsCommandUrgent {
            get {
                return ResourceManager.GetString("ComposeExtensionsCommandUrgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search urgent requests.
        /// </summary>
        public static string ComposeExtensionsCommandUrgentDescription {
            get {
                return ResourceManager.GetString("ComposeExtensionsCommandUrgentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe the problem.
        /// </summary>
        public static string descriptionPlaceholderText {
            get {
                return ResourceManager.GetString("descriptionPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string descriptionText {
            get {
                return ResourceManager.GetString("descriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name (max 50 characters).
        /// </summary>
        public static string displayName {
            get {
                return ResourceManager.GetString("displayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name here.
        /// </summary>
        public static string displayNamePlaceholder {
            get {
                return ResourceManager.GetString("displayNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropdown.
        /// </summary>
        public static string dropDown {
            get {
                return ResourceManager.GetString("dropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropdown options.
        /// </summary>
        public static string dropdownOptions {
            get {
                return ResourceManager.GetString("dropdownOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item text cannot be duplicate.
        /// </summary>
        public static string duplicateItem {
            get {
                return ResourceManager.GetString("duplicateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team url cannot be empty..
        /// </summary>
        public static string emptyTeamLink {
            get {
                return ResourceManager.GetString("emptyTeamLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request remote support quickly. Search requests and escalate to on call experts via group chat for urgent requests..
        /// </summary>
        public static string EndUserManifestFullDescription {
            get {
                return ResourceManager.GetString("EndUserManifestFullDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Support.
        /// </summary>
        public static string EndUserManifestName {
            get {
                return ResourceManager.GetString("EndUserManifestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helps request support and connect with experts quickly.
        /// </summary>
        public static string EndUserManifestShortDescription {
            get {
                return ResourceManager.GetString("EndUserManifestShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!.
        /// </summary>
        public static string genericError {
            get {
                return ResourceManager.GetString("genericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build form.
        /// </summary>
        public static string headerTitle {
            get {
                return ResourceManager.GetString("headerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Date.
        /// </summary>
        public static string inputDate {
            get {
                return ResourceManager.GetString("inputDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Text.
        /// </summary>
        public static string inputText {
            get {
                return ResourceManager.GetString("inputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid team url..
        /// </summary>
        public static string invalidTeamLink {
            get {
                return ResourceManager.GetString("invalidTeamLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading... Please wait.
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card configuration.
        /// </summary>
        public static string mainHeader {
            get {
                return ResourceManager.GetString("mainHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add more than 4 choices.
        /// </summary>
        public static string maxCheckBoxChoices {
            get {
                return ResourceManager.GetString("maxCheckBoxChoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum of only 4 components can be added in preview.
        /// </summary>
        public static string maxComponents {
            get {
                return ResourceManager.GetString("maxComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add more than 10 choices.
        /// </summary>
        public static string maxDropdownChoices {
            get {
                return ResourceManager.GetString("maxDropdownChoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name should not be more than 50 characters.
        /// </summary>
        public static string maxLengthDisplayName {
            get {
                return ResourceManager.GetString("maxLengthDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add more than 3 choices.
        /// </summary>
        public static string maxRadioChoices {
            get {
                return ResourceManager.GetString("maxRadioChoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 2 items expected.
        /// </summary>
        public static string minimumItems {
            get {
                return ResourceManager.GetString("minimumItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item text cannot be empty.
        /// </summary>
        public static string nonEmptyItem {
            get {
                return ResourceManager.GetString("nonEmptyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string normalSeverity {
            get {
                return ResourceManager.GetString("normalSeverity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to access the application.
        /// </summary>
        public static string notAuthorized {
            get {
                return ResourceManager.GetString("notAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name should not be empty.
        /// </summary>
        public static string notEmptyDisplayName {
            get {
                return ResourceManager.GetString("notEmptyDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder (max 50 characters).
        /// </summary>
        public static string placeholder {
            get {
                return ResourceManager.GetString("placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the placeholder text here.
        /// </summary>
        public static string placeholderText {
            get {
                return ResourceManager.GetString("placeholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string previewTitle {
            get {
                return ResourceManager.GetString("previewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Button.
        /// </summary>
        public static string radioButton {
            get {
                return ResourceManager.GetString("radioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio button choice options.
        /// </summary>
        public static string radioOptions {
            get {
                return ResourceManager.GetString("radioOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage support request and set up on call experts in team. Search urgent, assigned and unassigned requests right from expert team..
        /// </summary>
        public static string SmeManifestFullDescription {
            get {
                return ResourceManager.GetString("SmeManifestFullDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Support - Expert.
        /// </summary>
        public static string SmeManifestName {
            get {
                return ResourceManager.GetString("SmeManifestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert team bot to handle user requests and set on call experts..
        /// </summary>
        public static string SmeManifestShortDescription {
            get {
                return ResourceManager.GetString("SmeManifestShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request type.
        /// </summary>
        public static string staticDropdown {
            get {
                return ResourceManager.GetString("staticDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select request type.
        /// </summary>
        public static string staticDropdownPlaceholder {
            get {
                return ResourceManager.GetString("staticDropdownPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved successfully.
        /// </summary>
        public static string successPublish {
            get {
                return ResourceManager.GetString("successPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team link.
        /// </summary>
        public static string teamLink {
            get {
                return ResourceManager.GetString("teamLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is it about?.
        /// </summary>
        public static string titleText {
            get {
                return ResourceManager.GetString("titleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name should be unique.
        /// </summary>
        public static string uniqueDisplayName {
            get {
                return ResourceManager.GetString("uniqueDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent.
        /// </summary>
        public static string urgentSeverity {
            get {
                return ResourceManager.GetString("urgentSeverity", resourceCulture);
            }
        }
    }
}
